package com.randomlychosenbytes.jlocker.dialogs;

import com.randomlychosenbytes.jlocker.manager.DataManager;

import java.util.List;

public class SettingsDialog extends javax.swing.JDialog {
    DataManager dataManager;

    public SettingsDialog(java.awt.Frame parent, DataManager dataManager, boolean modal) {
        super(parent, modal);
        initComponents();

        this.dataManager = dataManager;

        // button that is clicked when you hit enter
        getRootPane().setDefaultButton(okButton);

        // focus in the middle
        setLocationRelativeTo(null);

        int numBackups = (Integer) dataManager.getSettings().get("NumOfBackups");
        numBackupsSlider.setValue(numBackups);
        numBackupsTextField.setText(Integer.toString(numBackups));

        updateLockerMinSizesTextField();
    }

    public final void updateLockerMinSizesTextField() {
        String text = "";

        List<Integer> minSizes = (List<Integer>) dataManager.getSettings().get("LockerMinSizes");

        for (int i = 0; i < minSizes.size(); i++) {
            if (i != 0) {
                text += ", ";
            }

            text += minSizes.get(minSizes.size() - i - 1).toString();
        }

        lockerMinSizesTextField.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        backupPanel = new javax.swing.JPanel();
        numBackupsLabel = new javax.swing.JLabel();
        numBackupsTextField = new javax.swing.JTextField();
        numBackupsSlider = new javax.swing.JSlider();
        lockerMinSizesLabel = new javax.swing.JLabel();
        lockerMinSizesTextField = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Einstellungen");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        backupPanel.setLayout(new java.awt.GridBagLayout());

        numBackupsLabel.setText("Anzahl der Backups");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        backupPanel.add(numBackupsLabel, gridBagConstraints);

        numBackupsTextField.setEditable(false);
        numBackupsTextField.setColumns(3);
        backupPanel.add(numBackupsTextField, new java.awt.GridBagConstraints());

        mainPanel.add(backupPanel);

        numBackupsSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numBackupsSliderStateChanged(evt);
            }
        });
        mainPanel.add(numBackupsSlider);

        lockerMinSizesLabel.setText("Mindestgrößen für Schließfächer");
        mainPanel.add(lockerMinSizesLabel);

        lockerMinSizesTextField.setEditable(false);
        lockerMinSizesTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lockerMinSizesTextFieldMouseClicked(evt);
            }
        });
        mainPanel.add(lockerMinSizesTextField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(mainPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(buttonPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {//GEN-HEADEREND:event_okButtonActionPerformed
        dataManager.getSettings().put("NumOfBackups", numBackupsSlider.getValue());

        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void numBackupsSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_numBackupsSliderStateChanged
    {//GEN-HEADEREND:event_numBackupsSliderStateChanged
        int num = numBackupsSlider.getValue();
        numBackupsTextField.setText(Integer.toString(num));
    }//GEN-LAST:event_numBackupsSliderStateChanged

    private void lockerMinSizesTextFieldMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lockerMinSizesTextFieldMouseClicked
    {//GEN-HEADEREND:event_lockerMinSizesTextFieldMouseClicked
        new SetLockerMinimumSizesDialog(this, dataManager, true).setVisible(true);
    }//GEN-LAST:event_lockerMinSizesTextFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backupPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel lockerMinSizesLabel;
    private javax.swing.JTextField lockerMinSizesTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel numBackupsLabel;
    private javax.swing.JSlider numBackupsSlider;
    private javax.swing.JTextField numBackupsTextField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
